# sample of Brainsmart code

incl {
    # imported modules e. g. `lib/math` will be expected in `./lib/math.bs`
    lib/std,
}

decl {
    @count,
    @char,

    !main,
}

impl {
    !main {
        @count;
        .set 5;

        @char;
        .set 'F';

        !while(count) {
            @char;
            .out;

            @count;
            .dec;
        }

        @char;
        .set '\n';
        .out;
    }
}